version: "3.9"

services:
  postgres-local:
    image: postgres:15
    container_name: postgres-local
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    networks:
      - property-network
    restart: always

  property-service-local:
    image: property-service
    container_name: property-service-local
    ports:
      - "3004:3000" 
    env_file:
      - .env
    networks:
      - property-network
    volumes:
      - ./migrations:/app/services/property/migrations
    depends_on:
      - postgres-local
    restart: always

networks:
  property-network:
    driver: bridge

volumes:
  postgres_data_local:
